language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package; scripted'
after_script:
- ci/sbt-deploy.sh core generator
- ci/sbt-deploy-ivy.sh plugin
- rm -rf ci
- find $HOME/.ivy2 -name "*humbug*" -delete
env:
  global:
    secure: G9zfa2fM5+gYpDbLItDM9OQnCTgEW+KE3Yh6D0GP7TEuGVcOlNyTWOA+Z1u5xBu5l4SrgrpuKiTeTYuiHlxiCwX2PWOoNOG8pd0muTl/x0RYpZjuJNPNbdUQ3MtC48k4HBuAsQYW0hLsdwF9kMRFoFZkJqzrFNclIgldz7Rvbh4=
